version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    environment:
      - PORT=4000
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    restart: unless-stopped
    # volumes:
    #   - ./:/app # Uncomment for live code reload in dev 